name: roadsurfer_code_challenge
description: This is a code challenge for Roadsurfer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chopper: ^4.0.4
  flutter_bloc: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.1.1
  chopper_generator: ^4.0.3
  build_runner: ^2.1.5
  json_annotation: ^4.4.0
  test: ^1.21.0
  bloc_test: ^9.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
